#!/usr/bin/env bash

# Start the Nginx service
service nginx start

# Check if Nginx is listening on port 80
if ss -lntp | grep -q ':80'; then
	echo "Nginx is listening on port 80"
else
	# If not, update the Nginx configuration to listen on port 80
	sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-available/default.conf
	service nginx restart
	echo "Nginx is now listening on port 80"
fi
