#!/usr/bin/env bash
# "4-to_infinity_and_beyond"

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [[ -n $pid ]]; then
  kill "$pid"
  echo "4-to_infinity_and_beyond ($pid)."
else
  echo "4-to_infinity_and_beyond"
fi
