#!/usr/bin/env bash
#Now that you’ve parsed the Apache log file,

unique_entries=$(awk '{print $1 " " $9}' access.log | sort | uniq -c)

echo "$unique_entries" | awk '{print $2 " " $3 " " $1}' | sort -k3nr
