#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes

hour=0
minute=1
counter=1

printf "Hour:" $hour\n
while [ $counter -le 70 ]
do
  printf "%d\n" $minute
  ((minute++))
  if [ $minute -eq 60 ]
  then  
    ((hour++))
    minute=0
  fi

  if [ $hour -eq 13 ]
  then
    hour=1
  fi

  ((counter++))
done | head -n 70
